In [1]:
import pandas as pd
import numpy as np

# Data Before cleaning

In [39]:
data=pd.read_csv("/content/dirty_cafe_sales.csv")
data.head(12)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR

# Data Before cleaning

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

# Number of Empty Cells

In [4]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

# Exploring the data

# check duplication

In [5]:
data.duplicated().sum()

np.int64(0)

## Problems (NaN,UNKNOWN,ERROR)

In [6]:
data["Item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [7]:
data["Item"].value_counts()

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

In [8]:
data["Quantity"].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

In [9]:
data["Price Per Unit"].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN'],
      dtype=object)

In [10]:
data["Total Spent"].unique()

array(['4.0', '12.0', 'ERROR', '10.0', '20.0', '9.0', '16.0', '15.0',
       '25.0', '8.0', '5.0', '3.0', '6.0', nan, 'UNKNOWN', '2.0', '1.0',
       '7.5', '4.5', '1.5'], dtype=object)

In [11]:
data["Payment Method"].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [12]:
data["Location"].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [13]:
data["Location"].value_counts()

Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

# Handling All missing/invalid value

## Price Per Unit

In [14]:
# here i fill all UNKNOWN, ERROR, NaN with 0
# i will expect the price with its type of item , location

data["Price Per Unit"].replace(['UNKNOWN', 'ERROR'], 0 , inplace=True)
data["Price Per Unit"].fillna(0, inplace=True)
data["Price Per Unit"]=data["Price Per Unit"].astype(float)
data["Price Per Unit"].unique()

/tmp/ipykernel_2429/1512286362.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Price Per Unit"].replace(['UNKNOWN', 'ERROR'], 0 , inplace=True)

array([2. , 3. , 1. , 5. , 4. , 1.5, 0. ])

## Quantity

In [15]:
# here i fill all UNKNOWN, ERROR, NaN with 0
# i will expect the Quantity with its type of total price



data["Quantity"].replace(['UNKNOWN', 'ERROR'], 0 , inplace=True)
data["Quantity"].fillna(0, inplace=True)
data["Quantity"]=data["Quantity"].astype(int)
data["Quantity"].unique()

/tmp/ipykernel_2429/421785183.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Quantity"].replace(['UNKNOWN', 'ERROR'], 0 , inplace=True)

array([2, 4, 5, 3, 1, 0])

## Location

In [16]:
# here i fill all ERROR, NaN with UNKNOWN

data["Location"].replace(['ERROR'], 'UNKNOWN' , inplace=True)
data["Location"].fillna('UNKNOWN', inplace=True)
data["Location"].unique()

/tmp/ipykernel_2429/2266802818.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Location"].replace(['ERROR'], 'UNKNOWN' , inplace=True)

array(['Takeaway', 'In-store', 'UNKNOWN'], dtype=object)

## Payment Method

In [17]:
# here i fill all ERROR, NaN with UNKNOWN

data["Payment Method"].replace(['ERROR'], 'UNKNOWN' , inplace=True)
data["Payment Method"].fillna('UNKNOWN', inplace=True)
data["Payment Method"].unique()

/tmp/ipykernel_2429/2320849960.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Payment Method"].replace(['ERROR'], 'UNKNOWN' , inplace=True)

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet'], dtype=object)

## Item

In [18]:
# here i fill all ERROR, NaN with UNKNOWN

data["Item"].replace(['ERROR'], 'UNKNOWN' , inplace=True)
data["Item"].fillna('UNKNOWN', inplace=True)
data["Item"].unique()

/tmp/ipykernel_2429/2503591763.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Item"].replace(['ERROR'], 'UNKNOWN' , inplace=True)

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', 'Juice', 'Tea'], dtype=object)

## Total Spent

In [19]:
# here i fill all UNKNOWN, ERROR, NaN with 0

data["Total Spent"].replace(['UNKNOWN', 'ERROR'], 0 , inplace=True)
data["Total Spent"].fillna(0, inplace=True)
data["Total Spent"]=data["Total Spent"].astype(float)
data["Total Spent"].unique()

/tmp/ipykernel_2429/2090755476.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Total Spent"].replace(['UNKNOWN', 'ERROR'], 0 , inplace=True)

array([ 4. , 12. ,  0. , 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,
        3. ,  6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

## Transaction Date

In [20]:
# change to Date Type
data['Transaction Date'] = pd.to_datetime(data['Transaction Date'], errors='coerce')
# Forward Fill
data['Transaction Date'] = data['Transaction Date'].ffill()

## Make filtering to know the price of unit

In [21]:
# I use this filter to know the price of each item
# location not impact on price

result = data.groupby('Item').agg({
    'Price Per Unit': 'unique',
    'Location': 'unique'
}).reset_index()
result

,Item,Price Per Unit,Location
0,Cake,"[3.0, 0.0]","[In-store, UNKNOWN, Takeaway]"
1,Coffee,"[2.0, 0.0]","[Takeaway, In-store, UNKNOWN]"
2,Cookie,"[1.0, 0.0]","[In-store, Takeaway, UNKNOWN]"
3,Juice,"[3.0, 0.0]","[In-store, Takeaway, UNKNOWN]"
4,Salad,"[5.0, 0.0]","[UNKNOWN, Takeaway, In-store]"
5,Sandwich,"[4.0, 0.0]","[UNKNOWN, In-store, Takeaway]"
6,Smoothie,"[4.0, 0.0]","[UNKNOWN, In-store, Takeaway]"
7,Tea,"[1.5, 0.0]","[Takeaway, In-store, UNKNOWN]"
8,UNKNOWN,"[3.0, 1.5, 2.0, 1.0, 5.0, 0.0, 4.0]","[Takeaway, In-store, UNKNOWN]"

# تم عمل استبدال لكل القيم غير الصالحه و القيم الفارغه

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  int64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 625.1+ KB

## convert price_to_item

In [24]:
# I replace the missing values with its actual item based on its price
price_to_item_map = {
    3.0: 'Cake',
    2.0: 'Coffee',
    1.0: 'Cookie',
    5.0: 'Salad',
    4.0: 'Sandwich',
    1.5: 'Tea'
}

mask_item = (data['Item'] == 'UNKNOWN')

data.loc[mask_item, 'Item'] = data.loc[mask_item, 'Price Per Unit'].map(price_to_item_map)
data["Item"].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Sandwich', 'Tea',
       'Juice', nan], dtype=object)

## convert Item to price

In [25]:
# I have a price of items
# so i fill the null in item column with its price

Item_price = {
  'Cake': 3.0,
  'Coffee': 2.0,
  'Cookie': 1.0,
  'Juice': 3.0,
  'Salad': 5.0,
  'Sandwich': 4.0,
  'Smoothie': 4.0,
  'Tea': 1.5
}

mask = (data['Price Per Unit'] == 0)

data.loc[mask, 'Price Per Unit'] = data.loc[mask, 'Item'].map(Item_price)

data['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [26]:
data = data.dropna(subset=['Item'])

In [27]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

# تم عمل استبدال للقيم غير الصالحه ب القيم الحقيقه عن طريق قسم القيمه الكليه علي سعر الوحده الواحده

In [28]:

mask = (data['Quantity'] == 0)

data.loc[mask, 'Quantity'] = data.loc[mask, 'Total Spent'] / data.loc[mask, 'Price Per Unit']

In [29]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [30]:
data["Location"].value_counts()

Location
UNKNOWN     3936
Takeaway    3008
In-store    3002
Name: count, dtype: int64

In [31]:
data['Quantity'].value_counts()

Quantity
5    2096
2    2048
3    1936
4    1926
1    1920
0      20
Name: count, dtype: int64

# تم حذف القيم التي بها قيم غير صالحه و عددهم  هو 20 قيمه حتي تكون الداتا نظيفه 100 %

In [32]:
# drop to 20 row with zero value
data = data[data['Quantity'] != 0]

data = data.reset_index(drop=True)

#  القيم بعد التنظيف النهائي

In [33]:
data['Quantity'].value_counts()

Quantity
5    2096
2    2048
3    1936
4    1926
1    1920
Name: count, dtype: int64

## Total spent with 0 value (was NaN)

# تم عمل حساب للقيمه الكليه عن طريق ضرب الكميه المطلوبه مع سعر الوحده الواحده

In [34]:
# Total Spent = Quantity *Price Per Unit
# but with zero (was NaN and convert to 0 )
mask = (data['Total Spent'] == 0)

data.loc[mask, 'Total Spent'] = data.loc[mask, 'Quantity'] * data.loc[mask, 'Price Per Unit']
data["Total Spent"].unique()

array([ 4. , 12. , 10. , 20. ,  9. , 16. , 15. , 25. ,  8. ,  5. ,  3. ,
        6. ,  2. ,  1. ,  7.5,  4.5,  1.5])

# Data After cleaning

In [37]:
# Data After cleaning
data.head(13)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,UNKNOWN,2023-03-31
6,TXN_4433211,Cake,3,3.0,9.0,UNKNOWN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,Cake,5,3.0,15.0,UNKNOWN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,UNKNOWN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,2023-11-07
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9926 entries, 0 to 9925
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9926 non-null   object
 1   Item              9926 non-null   object
 2   Quantity          9926 non-null   int64
 3   Price Per Unit    9926 non-null   float64
 4   Total Spent       9926 non-null   float64
 5   Payment Method    9926 non-null   object
 6   Location          9926 non-null   object
 7   Transaction Date  9926 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 620.5+ KB